fix: fix Swagger page for ASA Manager
System.NotSupportedException: Ambiguous HTTP method for action - Mmm.Platform.IoT.AsaManager.WebService.v1.Controllers.RulesController.Forget (Mmm.Platform.IoT.AsaManager.WebService). Actions require an explicit HttpMethod binding for Swagger 2.0